server:
  port: 443
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: rabieimghi
    key-store-password: rabieimghi

spring:
  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yml
      lifecycle-management: start_only

  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #  url: jdbc:postgresql://localhost:5433/samurai
  #  username: samurai
  #  password: password


  jpa:
    properties:
      hibernate:
        default_schema: public



  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  autoconfigure:
    exclude:
      # - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  task:
    scheduling:
      enabled: true

  sonar:
    login: ${SONAR_PASSWORD}


