server:
  port: 443
  #ssl:
    #  enabled: true
    #key-alias: local_ssl
    #key-store: classpath:local-ssl.p12
    #key-store-type: PKCS12
    #key-password: rabieimghi
  #key-store-password: rabieimghi
jwt:
  auth:
    converter:
      resource-id: Hunters_league_api
      principal-attribute: preferred_username
spring:
  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yml
      lifecycle-management: start_only
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Hunters_league
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #  url: jdbc:postgresql://localhost:5433/samurai
  #  username: samurai
  #  password: password


  jpa:
    properties:
      hibernate:
        default_schema: public



  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  autoconfigure:
    exclude:
      # - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  task:
    scheduling:
      enabled: true

  sonar:
    login: ${SONAR_PASSWORD}


